language: python

python:
    - '2.7'
    - '3.4'

sudo: false

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    allow_failures:
        - python: '3.4'

services:
  - postgresql

env:
  matrix:
    - PRODUCTION=TRUE
  global:
    # GH_TOKEN env var. See http://docs.travis-ci.com/user/encryption-keys/
    - secure: fQVrTJV4FyBcRihbrd+MSvWtYHVFLXeX1uTOINZx121k88k1yyH6Qnh2cYpouMfXdTFMc4negTr3ceNqtljVD1za8Q6jWKk0Ht6MWTuDMb/4mynTKn7qufGe0+scJDueofeBymXthEXbRzh1O+1qEmVkxZUwoKCYXIb6Uk2KSeU= 
    - secure: BT+ndG5VAs3UxdrF7dTx7MK6SACHG8lf9ABfcAD1FgMi+gccT+R3b6FiQ6AcBn4P+1FqHnoxrOEL4PsxPBAUVLf+wjynOXBMI6Ee+bmUfqLvcP1WwCRK3WhSZpH5lSUr7TCxkGFX7ROOJLnqPScTgQhiWHbCzwV9RcAwHaKj1PM=

install:
    - pip install -U coveralls -r requirements.txt

before_script:
  - cp intranet/settings/travis_secret.py intranet/settings/secret.py
  - psql -c 'create database ion;' -U postgres

script:
  - coverage run --source=ion ./manage.py test
  - ./travis/build_docs.sh

after_success:
  - ./travis/push_docs.sh
  - coveralls

notifications:
    irc:
        channels: "chat.freenode.net#tjcsl-ion"
        skip_join: true
