language: python

python:
    - '2.7'
    - '3.4'

sudo: false

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/virtualenv

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log

matrix:
    allow_failures:
        - python: '3.4'

services:
  - postgresql

env:
  matrix:
    - PRODUCTION=TRUE
  global:
    # GH_TOKEN env var. See http://docs.travis-ci.com/user/encryption-keys/
    - secure: "fQVrTJV4FyBcRihbrd+MSvWtYHVFLXeX1uTOINZx121k88k1yyH6Qnh2cYpouMfXdTFMc4negTr3ceNqtljVD1za8Q6jWKk0Ht6MWTuDMb/4mynTKn7qufGe0+scJDueofeBymXthEXbRzh1O+1qEmVkxZUwoKCYXIb6Uk2KSeU=" 

install:
    # Hack to prevent pip/setuptools from being upgraded and screwing up the cache.
    - pip install -U -r requirements.txt pip==$(pip show pip|sed -n "s#^Version. \(.*\)#\1#p") setuptools==$(pip show setuptools|sed -n "s#^Version. \(.*\)#\1#p")

before_script:
  - cp intranet/settings/travis_secret.py intranet/settings/secret.py
  - psql -c 'create database ion;' -U postgres

script:
  - "./manage.py test"
  - "./travis/build_docs.sh"

after_success:
  - "./travis/push_docs.sh"

notifications:
    irc:
        channels: "chat.freenode.net#tjcsl-ion"
